Name=("Chinaza Nwanya")
Email=("nwanyachinaza@gmail.com")
Slack_username=("@Chinaza")
Twitter_handle=("@candace")
Biostack=("data analysis")
install.packages("stringdist")
library(stringdist)
Hamming_distance=cat(stringdist("@Chinaza", "@candace", method = 'hamming'))
Hamming_distance=cat(stringdist("@Chinaza", "@candace", method = 'hamming'))
Hamming_distance <- c(stringdist("@Chinaza", "@candace", method = 'hamming'))
cat(Name, Email, Slack_username, Biostack, Twitter_handle, Hamming_distance)
